theme: jekyll-theme-cayman

# Name of website.
title: Hardy Scheel

# Short description of your site.
description: Personal experiences and projects about software development, programming and computer science.

# The language of your website content.
lang: en

# If you are building a simple GitHub user page (https://username.github.io) then use these settings.
# url is the full website URL
# baseurl is the website's URL without the hostname
url: https://scheel.dev

# If you are building a GitHub project page then use these settings:
# url is the full website URL
# baseurl is the website's URL without the hostname
# url: "hardyscheel.github.io/a-simple-app"
# baseurl: "/a-simple-app"

timezone: "Germany/Berlin"

permalink: /blog/:title/
# permalink: /blog/:year-:month-:day-:title/

author: Hardy Scheel

# Show only a few blog entries per page.
paginate: 3
paginate_path: "/blog/page:num/"

# "true" or "false" to indicate whether to provide a download URL to download the project.
show_downloads: false

# Fill in your Google Analytics ID to track your website using GA.
google_analytics: UA-131417385-2